using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Selu383.SP26.Api.Data;
using Selu383.SP26.Api.Dtos;
using Selu383.SP26.Api.Entities;

namespace Selu383.SP26.Api.Controllers;

[ApiController]
[Route("api/locations")]
public class LocationsController : ControllerBase
{
    private readonly DataContext dataContext;

    public LocationsController(DataContext dataContext)
    {
        this.dataContext = dataContext;
    }

    [HttpGet]
    public async Task<ActionResult<IEnumerable<LocationDto>>> GetLocations()
    {
        var locations = await dataContext.Locations
            .AsNoTracking()
            .OrderBy(x => x.Id)
            .Select(x => new LocationDto
            {
                Id = x.Id,
                Name = x.Name,
                Address = x.Address,
                TableCount = x.TableCount
            })
            .ToListAsync();

        return Ok(locations);
    }

    [HttpGet("{id:int}")]
    public async Task<ActionResult<LocationDto>> GetLocationById(int id)
    {
        var location = await dataContext.Locations
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.Id == id);

        if (location == null)
        {
            return NotFound();
        }

        return Ok(new LocationDto
        {
            Id = location.Id,
            Name = location.Name,
            Address = location.Address,
            TableCount = location.TableCount
        });
    }

    [HttpPost]
    public async Task<ActionResult<LocationDto>> CreateLocation(LocationDto request)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var entity = new Location
        {
            // Id generated by database
            Name = request.Name,
            Address = request.Address,
            TableCount = request.TableCount
        };

        dataContext.Locations.Add(entity);
        await dataContext.SaveChangesAsync();

        var result = new LocationDto
        {
            Id = entity.Id,
            Name = entity.Name,
            Address = entity.Address,
            TableCount = entity.TableCount
        };
        return CreatedAtAction(nameof(GetLocationById), new { id = result.Id }, result);
    }

    [HttpPut("{id:int}")]
    public async Task<ActionResult<LocationDto>> UpdateLocation(int id, LocationDto request)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }
        if (id != request.Id)
        {
            return BadRequest("The route id must match the payload id.");
        }

        var entity = await dataContext.Locations.FirstOrDefaultAsync(x => x.Id == id);
        if (entity == null)
        {
            return NotFound();
        }

        entity.Name = request.Name;
        entity.Address = request.Address;
        entity.TableCount = request.TableCount;
        await dataContext.SaveChangesAsync();

        return Ok(new LocationDto
        {
            Id = entity.Id,
            Name = entity.Name,
            Address = entity.Address,
            TableCount = entity.TableCount
        });
    }

    [HttpDelete("{id:int}")]
    public async Task<IActionResult> DeleteLocation(int id)
    {
        var entity = await dataContext.Locations.FirstOrDefaultAsync(x => x.Id == id);
        if (entity == null)
        {
            return NotFound();
        }

        dataContext.Locations.Remove(entity);
        await dataContext.SaveChangesAsync();

        return Ok();
    }
}
